ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_FIRMWARE_NX_VERSION = $(SUMMIT_NX_RADIO_STACK_VERSION_VALUE)
SUMMIT_FIRMWARE_NX_SOURCE = summit-nx61x-firmware-$(SUMMIT_FIRMWARE_NX_VERSION).tar.bz2
SUMMIT_FIRMWARE_NX_STRIP_COMPONENTS = 0
SUMMIT_FIRMWARE_NX_LICENSE = Ezurio
SUMMIT_FIRMWARE_NX_LICENSE_FILES = LICENSE

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_NX_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_NX_VERSION)
else
  SUMMIT_FIRMWARE_NX_SITE = $(SUMMIT_RADIO_URI_BASE_NX)-$(SUMMIT_FIRMWARE_NX_VERSION)
endif

define SUMMIT_FIRMWARE_NX_INSTALL_TARGET_CMDS
  rsync -rlpDWK --no-perms --inplace --exclude '.*' --exclude LICENSE $(@D) $(TARGET_DIR)/
endef

endif

$(eval $(generic-package))
