ifeq ($(BR2_LRD_DEVEL_BUILD),y)
else
SUMMIT_FIRMWARE_NX_VERSION = $(SUMMIT_NX_RADIO_STACK_VERSION_VALUE)
SUMMIT_FIRMWARE_NX_SOURCE =
SUMMIT_FIRMWARE_NX_LICENSE = GPL-2.0
SUMMIT_FIRMWARE_NX_LICENSE_FILES = COPYING

ifeq ($(MSD_60_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_NX_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_NX_VERSION)
else
  SUMMIT_FIRMWARE_NX_SITE = https://github.com/LairdCP/SonaNX-Release-Packages/releases/tag/LRD-REL-$(SUMMIT_FIRMWARE_NX_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_NX_NX61X),y)
SUMMIT_FIRMWARE_NX_EXTRA_DOWNLOADS += laird-nx61x-firmware-$(SUMMIT_FIRMWARE_NX_VERSION).tar.bz2
endif

define SUMMIT_FIRMWARE_NX_INSTALL_TARGET_CMDS
	$(foreach n,$(SUMMIT_FIRMWARE_NX_EXTRA_DOWNLOADS),tar -xjf $($(PKG)_DL_DIR)/$(n) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch $(sep))
endef

endif

$(eval $(generic-package))
