ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_REG45N_VERSION = $(SUMMIT_MSD_RADIO_STACK_VERSION_VALUE)
SUMMIT_REG45N_SOURCE = reg45n-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REG45N_VERSION).tar.bz2
SUMMIT_REG45N_STRIP_COMPONENTS = 0
SUMMIT_REG45N_LICENSE = Ezurio
SUMMIT_REG45N_LICENSE_FILES = LICENSE.ezurio

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
	SUMMIT_REG45N_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/reg45n/laird/$(SUMMIT_REG45N_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_REG45N_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_REG45N_SOURCE)
  SUMMIT_REG45N_SITE = file://$(BASE_DIR)/../reg45n-$(SUMMIT_RADIO_STACK_ARCH)/images
else
	SUMMIT_REG45N_SITE = $(SUMMIT_RADIO_URI_BASE_MSD)-$(SUMMIT_REG45N_VERSION)
endif

define SUMMIT_REG45N_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REG45N_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REG45N_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REG45N_SOURCE) $(@D)/$(SUMMIT_REG45N_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REG45N_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REG45N_POST_EXTRACT_HOOKS += SUMMIT_REG45N_POST_EXTRACT

define SUMMIT_REG45N_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 755 -t $(TARGET_DIR)/usr/bin $(@D)/lru $(@D)/smu_cli $(@D)/tcmd.sh
	$(INSTALL) -D -m 644 -t $(TARGET_DIR)/lib/firmware/ath6k/AR6003/hw2.1.1/ $(@D)/utf*.bin
endef

endif

$(eval $(generic-package))
