ifeq ($(BR2_LRD_DEVEL_BUILD),y)
else
SUMMIT_FIRMWARE_LWB_IF_VERSION = $(call qstrip,$(SUMMIT_LWB_RADIO_STACK_VERSION_VALUE))
SUMMIT_FIRMWARE_LWB_IF_SOURCE =
SUMMIT_FIRMWARE_LWB_IF_LICENSE = GPL-2.0
SUMMIT_FIRMWARE_LWB_IF_LICENSE_FILES = COPYING

ifeq ($(MSD_60_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_LWB_IF_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_LWB_IF_VERSION)
else
  SUMMIT_FIRMWARE_LWB_IF_SITE = https://github.com/LairdCP/Sterling-LWB-and-LWB5-Release-Packages/releases/tag/LRD-REL-$(SUMMIT_FIRMWARE_LWB_IF_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB_FCC),y)
SUMMIT_FIRMWARE_LWB_IF_LWB_PKGS += fcc
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB_ETSI),y)
SUMMIT_FIRMWARE_LWB_IF_LWB_PKGS += etsi
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB_JP),y)
SUMMIT_FIRMWARE_LWB_IF_LWB_PKGS += jp
endif

SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += $(foreach n,$(SUMMIT_FIRMWARE_LWB_IF_LWB_PKGS),laird-lwb-$(n)-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2)

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5_FCC),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5_PKGS += fcc
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5_IC),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5_PKGS += ic
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5_ETSI),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5_PKGS += etsi
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5_JP),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5_PKGS += jp
endif

SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += $(foreach n,$(SUMMIT_FIRMWARE_LWB_IF_LWB5_PKGS),laird-lwb5-$(n)-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2)

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_SDIO_DIV),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += sdio-div
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_SDIO_SA),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += sdio-sa
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_SDIO_SA_M2),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += sdio-sa-m2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_USB_DIV),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += usb-div
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_USB_SA),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += usb-sa
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_USB_SA_M2),y)
SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS += usb-sa-m2
endif

SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += $(foreach n,$(SUMMIT_FIRMWARE_LWB_IF_LWB5PLUS_PKGS),laird-lwb5plus-$(n)-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2)

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_LWBPLUS),y)
SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += laird-lwbplus-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_IF573_SDIO),y)
SUMMIT_FIRMWARE_LWB_IF_IF573_PKGS += sdio
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_IF573_PCIE),y)
SUMMIT_FIRMWARE_LWB_IF_IF573_PKGS += pcie
endif

SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += $(foreach n,$(SUMMIT_FIRMWARE_LWB_IF_IF573_PKGS),laird-if573-$(n)-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2)

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_LWB_IF_IF513),y)
SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS += laird-if513-firmware-$(SUMMIT_FIRMWARE_LWB_IF_VERSION).tar.bz2
endif

define SUMMIT_FIRMWARE_LWB_IF_INSTALL_TARGET_CMDS
	$(foreach n,$(SUMMIT_FIRMWARE_LWB_IF_EXTRA_DOWNLOADS),tar -xjf $($(PKG)_DL_DIR)/$(n) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch $(sep))
endef

endif

$(eval $(generic-package))
