ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_REGCYPRESS_VERSION = $(SUMMIT_LWB_RADIO_STACK_VERSION_VALUE)
SUMMIT_REGCYPRESS_SOURCE = regCypress-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REGCYPRESS_VERSION).tar.bz2
SUMMIT_REGCYPRESS_STRIP_COMPONENTS = 0
SUMMIT_REGLWBPLUS_LICENSE = Cypress
SUMMIT_REGLWBPLUS_LICENSE_FILES = FOSS_README.txt

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_REGCYPRESS_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/regCypress/laird/$(SUMMIT_REGCYPRESS_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_REGCYPRESS_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_REGCYPRESS_SOURCE)
  SUMMIT_REGCYPRESS_SITE = file://$(BASE_DIR)/../regLWB-$(SUMMIT_RADIO_STACK_ARCH)/images
else
  SUMMIT_REGCYPRESS_SITE = $(SUMMIT_RADIO_URI_BASE_LWB)-$(SUMMIT_REGCYPRESS_VERSION)
endif

define SUMMIT_REGCYPRESS_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REGCYPRESS_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REGCYPRESS_SOURCE) $(@D)/$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REGCYPRESS_POST_EXTRACT_HOOKS += SUMMIT_REGCYPRESS_POST_EXTRACT

define SUMMIT_REGCYPRESS_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 775 -t $(TARGET_DIR)/usr/bin $(@D)/wl
	$(INSTALL) -D -m 644 -t $(TARGET_DIR)/lib/firmware/brcm $(@D)/brcmfmac*
endef

endif

$(eval $(generic-package))
