SUMMIT_REGCYPRESS_VERSION = $(SUMMIT_60_RADIO_STACK_VERSION_VALUE)
SUMMIT_REGCYPRESS_SOURCE = regCypress-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REGCYPRESS_VERSION).tar.bz2
SUMMIT_REGCYPRESS_STRIP_COMPONENTS = 0
SUMMIT_REGCYPRESS_LICENSE = GPL-2.0

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
SUMMIT_REGCYPRESS_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/regCypress/laird/$(SUMMIT_REGCYPRESS_VERSION)
else
SUMMIT_REGCYPRESS_SITE = $(SUMMIT_RADIO_URI_BASE_LWB)-$(SUMMIT_REGCYPRESS_VERSION)
endif

define SUMMIT_REGCYPRESS_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REGCYPRESS_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REGCYPRESS_SOURCE) $(@D)/$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REGCYPRESS_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REGCYPRESS_POST_EXTRACT_HOOKS += SUMMIT_REGCYPRESS_POST_EXTRACT

define SUMMIT_REGCYPRESS_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 775 -t $(TARGET_DIR)/usr/bin $(@D)/wl
	$(INSTALL) -D -m 644 -t $(TARGET_DIR)/lib/firmware/brcfmac $(@D)/brcmfmac*
endef

$(eval $(generic-package))
