SUMMIT_REGIF573_VERSION = $(SUMMIT_60_RADIO_STACK_VERSION_VALUE)
SUMMIT_REGIF573_SOURCE = regIF573-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REGIF573_VERSION).tar.bz2
SUMMIT_REGIF573_STRIP_COMPONENTS = 0
SUMMIT_REGIF573_LICENSE = GPL-2.0

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
SUMMIT_REGIF573_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/regIF573/laird/$(SUMMIT_REGIF573_VERSION)
else
SUMMIT_REGIF573_SITE = $(SUMMIT_RADIO_URI_BASE_60)/LRD-REL-$(SUMMIT_REGIF573_VERSION)
endif

define SUMMIT_REGIF573_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REGIF573_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REGIF573_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REGIF573_SOURCE) $(@D)/$(SUMMIT_REGIF573_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REGIF573_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REGIF573_POST_EXTRACT_HOOKS += SUMMIT_REGIF573_POST_EXTRACT

ifneq ($(BR2_PACKAGE_BLUEZ5_UTILS)$(BR2_PACKAGE_BLUEZ4_UTILS),)
define SUMMIT_REGIF573_BTLRU_INSTALL_TARGET_CMD
	$(INSTALL) -D -m 755 -t $(TARGET_DIR)/usr/bin $(@D)/btlru 
endef
endif

define SUMMIT_REGIF573_INSTALL_TARGET_CMDS
	$(SUMMIT_REGIF573_BTLRU_INSTALL_TARGET_CMD)
	$(INSTALL) -D -m 775 -t $(TARGET_DIR)/usr/bin $(@D)/lru
	$(INSTALL) -D -m 644 -t $(TARGET_DIR)/lib/firmware/cypress $(@D)/cyfmac*
endef

$(eval $(generic-package))
