SUMMIT_REGLWBPLUS_VERSION = $(SUMMIT_60_RADIO_STACK_VERSION_VALUE)
SUMMIT_REGLWBPLUS_SOURCE = regLWBplus-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REGLWBPLUS_VERSION).tar.bz2
SUMMIT_REGLWBPLUS_STRIP_COMPONENTS = 0
SUMMIT_REGLWBPLUS_LICENSE = GPL-2.0

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
SUMMIT_REGLWBPLUS_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/regLWBplus/laird/$(SUMMIT_REGLWBPLUS_VERSION)
else
SUMMIT_REGLWBPLUS_SITE = $(SUMMIT_RADIO_URI_BASE_LWB)-$(SUMMIT_REGLWBPLUS_VERSION)
endif

define SUMMIT_REGLWBPLUS_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REGLWBPLUS_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REGLWBPLUS_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REGLWBPLUS_SOURCE) $(@D)/$(SUMMIT_REGLWBPLUS_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REGLWBPLUS_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REGLWBPLUS_POST_EXTRACT_HOOKS += SUMMIT_REGLWBPLUS_POST_EXTRACT

ifneq ($(BR2_PACKAGE_BLUEZ5_UTILS)$(BR2_PACKAGE_BLUEZ4_UTILS),)
define SUMMIT_REGLWBPLUS_BTLRU_INSTALL_TARGET_CMD
	$(INSTALL) -D -m 755 -t $(TARGET_DIR)/usr/bin $(@D)/btlru 
endef
endif

define SUMMIT_REGLWBPLUS_INSTALL_TARGET_CMDS
	$(SUMMIT_REGLWBPLUS_BTLRU_INSTALL_TARGET_CMD)
	$(INSTALL) -D -m 775 -t $(TARGET_DIR)/usr/bin $(@D)/lru
	$(INSTALL) -D -m 644 -t $(TARGET_DIR)/lib/firmware/brcfmac $(@D)/brcmfmac*
endef

$(eval $(generic-package))
