ifneq ($(BR2_LRD_DEVEL_BUILD),y)
SUMMIT_FIRMWARE_BDSDMAC_VERSION = $(call qstrip,$(SUMMIT_BDSDMAC_RADIO_STACK_VERSION_VALUE))
SUMMIT_FIRMWARE_BDSDMAC_SOURCE =
SUMMIT_FIRMWARE_BDSDMAC_LICENSE = GPL-2.0
SUMMIT_FIRMWARE_BDSDMAC_LICENSE_FILES = COPYING

ifeq ($(MSD_60_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_BDSDMAC_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_BDSDMAC_VERSION)
else
  SUMMIT_FIRMWARE_BDSDMAC_SITE = https://github.com/LairdCP/BDSDMAC-Release-Packages/releases/tag/LRD-REL-$(SUMMIT_FIRMWARE_BDSDMAC_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_BDSDMAC),y)
SUMMIT_FIRMWARE_BDSDMAC_EXTRA_DOWNLOADS += laird-bdsdmac-firmware-$(SUMMIT_FIRMWARE_BDSDMAC_VERSION).tar.bz2
endif

define SUMMIT_FIRMWARE_BDSDMAC_INSTALL_TARGET_CMDS
	$(foreach n,$(SUMMIT_FIRMWARE_BDSDMAC_EXTRA_DOWNLOADS),tar -xjf $($(PKG)_DL_DIR)/$(n) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch $(sep))
endef

endif

$(eval $(generic-package))
