ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_FIRMWARE_BDSDMAC_VERSION = $(call qstrip,$(SUMMIT_BDSDMAC_RADIO_STACK_VERSION_VALUE))
SUMMIT_FIRMWARE_BDSDMAC_SOURCE = summit-bdsdmac-firmware-$(SUMMIT_FIRMWARE_BDSDMAC_VERSION).tar.bz2
SUMMIT_FIRMWARE_BDSDMAC_STRIP_COMPONENTS = 0
SUMMIT_FIRMWARE_BDSDMAC_LICENSE = QCA
SUMMIT_FIRMWARE_BDSDMAC_LICENSE_FILES = LICENSE.qca_firmware NOTICE.qca_firmware

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_BDSDMAC_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_BDSDMAC_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_FIRMWARE_BDSDMAC_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_FIRMWARE_BDSDMAC_DOWNLOADS)
  SUMMIT_FIRMWARE_BDSDMAC_SITE = file://$(BASE_DIR)/../firmware/images
else
  SUMMIT_FIRMWARE_BDSDMAC_SITE = $(SUMMIT_RADIO_URI_BASE_BDSDMAC)-$(SUMMIT_FIRMWARE_BDSDMAC_VERSION)
endif

define SUMMIT_FIRMWARE_BDSDMAC_INSTALL_TARGET_CMDS
  rsync -rlpDWK --no-perms --inplace $(@D)/lib $(TARGET_DIR)
endef

endif

$(eval $(generic-package))
