ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_REGTI351_VERSION = $(SUMMIT_TI_RADIO_STACK_VERSION_VALUE)
SUMMIT_REGTI351_SOURCE = regTI351-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_REGTI351_VERSION).tar.bz2
SUMMIT_REGTI351_STRIP_COMPONENTS = 0
SUMMIT_REGTI351_LICENSE = Ezurio
SUMMIT_REGTI351_LICENSE_FILES = LICENSE.ezurio

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_REGTI351_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/regTI351/laird/$(SUMMIT_REGTI351_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_REGTI351_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_REGTI351_SOURCE)
  SUMMIT_REGTI351_SITE = file://$(BASE_DIR)/../regTI351-$(SUMMIT_RADIO_STACK_ARCH)/images
else
  SUMMIT_REGTI351_SITE = $(SUMMIT_RADIO_URI_BASE_TI)-$(SUMMIT_REGTI351_VERSION)
endif

define SUMMIT_REGTI351_POST_EXTRACT
	(cd $(@D) && ./$(SUMMIT_REGTI351_SOURCE:%.tar.bz2=%.sh) tar)
	tar -xvjf $(@D)/$(SUMMIT_REGTI351_SOURCE) -C $(@D)
	rm $(@D)/$(SUMMIT_REGTI351_SOURCE) $(@D)/$(SUMMIT_REGTI351_SOURCE:%.tar.bz2=%.sh) $(@D)/$(SUMMIT_REGTI351_SOURCE:%.tar.bz2=%.sha)
endef

SUMMIT_REGTI351_POST_EXTRACT_HOOKS += SUMMIT_REGTI351_POST_EXTRACT

ifneq ($(BR2_PACKAGE_BLUEZ5_UTILS)$(BR2_PACKAGE_BLUEZ4_UTILS),)
define SUMMIT_REGTI351_BTLRU_INSTALL_TARGET_CMD
	$(INSTALL) -D -m 755 -t $(TARGET_DIR)/usr/bin $(@D)/btlru 
endef
endif

define SUMMIT_REGTI351_INSTALL_TARGET_CMDS
	$(SUMMIT_REGTI351_BTLRU_INSTALL_TARGET_CMD)
	$(INSTALL) -D -m 775 -t $(TARGET_DIR)/usr/bin $(@D)/lru
endef

endif

$(eval $(generic-package))
