ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_FIRMWARE_VERSION = $(call qstrip,$(SUMMIT_60_RADIO_STACK_VERSION_VALUE))
SUMMIT_FIRMWARE_SOURCE =
SUMMIT_FIRMWARE_LICENSE = Ezurio
SUMMIT_FIRMWARE_LICENSE_FILES = COPYING

ifeq ($(MSD_60_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_VERSION)
else
  SUMMIT_FIRMWARE_SITE = $(SUMMIT_RADIO_URI_BASE_60)-$(SUMMIT_FIRMWARE_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_SDIO_UART),y)
SUMMIT_FIRMWARE_60_PKGS += sdio-uart
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_SDIO_SDIO),y)
SUMMIT_FIRMWARE_60_PKGS += sdio-sdio
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_PCIE_UART),y)
SUMMIT_FIRMWARE_60_PKGS += pcie-uart
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_PCIE_USB),y)
SUMMIT_FIRMWARE_60_PKGS += pcie-usb
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_USB_USB),y)
SUMMIT_FIRMWARE_60_PKGS += usb-usb
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_SOM8MP),y)
SUMMIT_FIRMWARE_EXTRA_DOWNLOADS += summit-som8mp-radio-firmware-$(SUMMIT_FIRMWARE_VERSION).tar.bz2
endif

SUMMIT_FIRMWARE_EXTRA_DOWNLOADS += $(foreach n,$(SUMMIT_FIRMWARE_60_PKGS),summit-60-radio-firmware-$(n)-$(SUMMIT_FIRMWARE_VERSION).tar.bz2)

define SUMMIT_FIRMWARE_INSTALL_TARGET_CMDS
	$(foreach n,$(SUMMIT_FIRMWARE_EXTRA_DOWNLOADS),tar -xjf $($(PKG)_DL_DIR)/$(n) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch $(sep))
endef

endif

$(eval $(generic-package))
