#############################################################
#
# Summit Supplicant Libraries
#
#############################################################

ifneq ($(BR2_LRD_DEVEL_BUILD),y)

ifeq ($(BR2_PACKAGE_SUMMIT_SUPPLICANT_LIBS_LEGACY),y)
SUMMIT_SUPPLICANT_LIBS_VERSION = $(call qstrip,$(SUMMIT_MSD_RADIO_STACK_VERSION_VALUE))
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_MSD)-$(SUMMIT_SUPPLICANT_LIBS_VERSION)
SUMMIT_SUPPLICANT_LIBS_SOURCE = summit_supplicant_libs_legacy-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_SUPPLICANT_LIBS_VERSION).tar.bz2
else
SUMMIT_SUPPLICANT_LIBS_VERSION = $(call qstrip,$(SUMMIT_60_RADIO_STACK_VERSION_VALUE))
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_60)-$(SUMMIT_SUPPLICANT_LIBS_VERSION)
SUMMIT_SUPPLICANT_LIBS_SOURCE = summit_supplicant_libs-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_SUPPLICANT_LIBS_VERSION).tar.bz2
endif

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/summit_supplicant/laird/$(SUMMIT_SUPPLICANT_LIBS_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_SUPPLICANT_LIBS_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_SUPPLICANT_LIBS_SOURCE)
  SUMMIT_SUPPLICANT_LIBS_SITE = file://$(BASE_DIR)/../summit_supplicant_libs-$(SUMMIT_RADIO_STACK_ARCH)/images
endif

SUMMIT_SUPPLICANT_LIBS_LICENSE = Ezurio
SUMMIT_SUPPLICANT_LIBS_LICENSE_FILES = LICENSE.ezurio
SUMMIT_SUPPLICANT_LIBS_INSTALL_STAGING = YES

define SUMMIT_SUPPLICANT_LIBS_INSTALL_TARGET_CMDS
	rsync -rlpDWK --no-perms --inplace --exclude=libsdc_sdk.so $(@D)/usr/lib $(TARGET_DIR)/usr/lib
endef

ifeq ($(BR2_PACKAGE_SUMMIT_SUPPLICANT_LIBS_LEGACY),y)
define SUMMIT_SUPPLICANT_LIBS_LEGACY_INSTALL_STAGING_CMDS
	rsync -rlpDWK --no-perms --inplace $(@D)/usr/include $(TARGET_DIR)/usr/include
endef
endif

define SUMMIT_SUPPLICANT_LIBS_INSTALL_STAGING_CMDS
	rsync -rlpDWK --no-perms --inplace $(@D)/usr/lib/lib* $(TARGET_DIR)/usr/lib
	$(SUMMIT_SUPPLICANT_LIBS_LEGACY_INSTALL_STAGING_CMDS)
endef

endif

$(eval $(generic-package))
