#############################################################
#
# Summit Supplicant Libraries
#
#############################################################
ifeq ($(BR2_PACKAGE_SUMMIT_SUPPLICANT_LIBS_LEGACY),y)
SUMMIT_SUPPLICANT_LIBS_VERSION = $(call qstrip,$(SUMMIT_MSD_RADIO_STACK_VERSION_VALUE))
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_MSD)/LRD-REL-$(SUMMIT_SUPPLICANT_LIBS_VERSION)
SUMMIT_SUPPLICANT_LIBS_EXTRA_DOWNLOADS = summit_supplicant_libs_legacy-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_SUPPLICANT_LIBS_VERSION).tar.bz2
else
SUMMIT_SUPPLICANT_LIBS_VERSION = $(call qstrip,$(SUMMIT_60_RADIO_STACK_VERSION_VALUE))
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_60)/LRD-REL-$(SUMMIT_SUPPLICANT_LIBS_VERSION)
SUMMIT_SUPPLICANT_LIBS_EXTRA_DOWNLOADS = summit_supplicant_libs-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_SUPPLICANT_LIBS_VERSION).tar.bz2
endif

ifeq ($(MSD_LIBS_SOURCE_LOCATION),laird_internal)
SUMMIT_SUPPLICANT_LIBS_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/summit_supplicant/laird/$(SUMMIT_SUPPLICANT_LIBS_VERSION)
endif

SUMMIT_SUPPLICANT_LIBS_SOURCE =
SUMMIT_SUPPLICANT_LIBS_LICENSE = BSD-3-Clause

SUMMIT_SUPPLICANT_LIBS_INSTALL_STAGING = YES

define SUMMIT_SUPPLICANT_LIBS_INSTALL_TARGET_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(SUMMIT_SUPPLICANT_LIBS_EXTRA_DOWNLOADS) -C $(TARGET_DIR) --keep-directory-symlink --no-overwrite-dir --touch \
		--exclude=usr/include --exclude=usr/lib/libsdc_sdk.so
endef

ifeq ($(BR2_PACKAGE_SUMMIT_SUPPLICANT_LIBS_LEGACY),y)
SUMMIT_SUPPLICANT_LIBS_EXTRACT=usr/include
endif
define SUMMIT_SUPPLICANT_LIBS_INSTALL_STAGING_CMDS
	tar -xjf $($(PKG)_DL_DIR)/$(SUMMIT_SUPPLICANT_LIBS_EXTRA_DOWNLOADS) -C $(STAGING_DIR) --keep-directory-symlink --no-overwrite-dir --touch \
		--wildcards $(SUMMIT_SUPPLICANT_LIBS_EXTRACT) usr/lib/lib*
endef

$(eval $(generic-package))
