ifneq ($(BR2_LRD_DEVEL_BUILD),y)

SUMMIT_FIRMWARE_TI_VERSION = $(call qstrip,$(SUMMIT_TI_RADIO_STACK_VERSION_VALUE))
SUMMIT_FIRMWARE_TI_SOURCE = $(firstword $(SUMMIT_FIRMWARE_TI_DOWNLOADS))
SUMMIT_FIRMWARE_TI_EXTRA_DOWNLOADS = $(filter-out $(SUMMIT_FIRMWARE_TI_SOURCE),$(SUMMIT_FIRMWARE_TI_DOWNLOADS))
SUMMIT_FIRMWARE_TI_STRIP_COMPONENTS = 0
SUMMIT_FIRMWARE_TI_LICENSE = Ezurio
SUMMIT_FIRMWARE_TI_LICENSE_FILES = LICENSE

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_FIRMWARE_TI_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/firmware/$(SUMMIT_FIRMWARE_TI_VERSION)
else
  SUMMIT_FIRMWARE_TI_SITE = $(SUMMIT_RADIO_URI_BASE_TI)-$(SUMMIT_FIRMWARE_TI_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_AU),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-AU-firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_CA),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-CA_firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_EU),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-EU-firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_JP),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-JP-firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_US),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-US-firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

ifeq ($(BR2_PACKAGE_SUMMIT_FIRMWARE_TI_351_WW),y)
SUMMIT_FIRMWARE_TI_DOWNLOADS += summit-ti351-WW-firmware-$(SUMMIT_FIRMWARE_TI_VERSION).tar.bz2
endif

define SUMMIT_FIRMWARE_TI_EXTRACT_HOOK
	$(foreach n,$(SUMMIT_FIRMWARE_TI_EXTRA_DOWNLOADS),tar -xjf $($(PKG)_DL_DIR)/$(n) -C $(@D) --keep-directory-symlink --no-overwrite-dir $(sep))
endef

SUMMIT_FIRMWARE_TI_POST_EXTRACT_HOOKS += SUMMIT_FIRMWARE_TI_EXTRACT_HOOK

define SUMMIT_FIRMWARE_TI_INSTALL_TARGET_CMDS
  rsync -rlpDWK --no-perms --inplace --exclude '.*' --exclude LICENSE $(@D) $(TARGET_DIR)/
endef

endif

$(eval $(generic-package))
