ifneq ($(BR2_LRD_DEVEL_BUILD),y)
SUMMIT_ADAPTIVE_WW_VERSION = $(call qstrip,$(SUMMIT_60_RADIO_STACK_VERSION_VALUE))
SUMMIT_ADAPTIVE_WW_LICENSE = LGPL-2.1
SUMMIT_ADAPTIVE_WW_STRIP_COMPONENTS = 0
SUMMIT_ADAPTIVE_WW_LICENSE = Ezurio
SUMMIT_ADAPTIVE_WW_LICENSE_FILES = LICENSE.ezurio

SUMMIT_ADAPTIVE_WW_SOURCE = adaptive_ww-$(SUMMIT_RADIO_STACK_ARCH)-$(SUMMIT_ADAPTIVE_WW_VERSION).tar.bz2

ifeq ($(MSD_BINARIES_SOURCE_LOCATION),laird_internal)
  SUMMIT_ADAPTIVE_WW_SITE = $(SUMMIT_RADIO_URI_BASE_INTERNAL)/adaptive_ww/laird/$(SUMMIT_ADAPTIVE_WW_VERSION)
else ifeq ($(MSD_BINARIES_SOURCE_LOCATION),local)
  SUMMIT_ADAPTIVE_WW_VERSION = 0.$(BR2_SUMMIT_BRANCH).0.0
  BR_NO_CHECK_HASH_FOR += $(SUMMIT_ADAPTIVE_WW_SOURCE)
  SUMMIT_ADAPTIVE_WW_SITE = file://$(BASE_DIR)/../adaptive_ww-$(SUMMIT_RADIO_STACK_ARCH)/images
else
  SUMMIT_ADAPTIVE_WW_SITE = $(SUMMIT_RADIO_URI_BASE_60)-$(SUMMIT_ADAPTIVE_WW_VERSION)
endif

ifeq ($(BR2_PACKAGE_SUMMIT_ADAPTIVE_WW_MODE_LITE),y)
AWM_PARAMS += -M lite
endif

ifeq ($(BR2_PACKAGE_SUMMIT_ADAPTIVE_WW_INTF_AP),y)
AWM_PARAMS += -F AP
else ifeq ($(BR2_PACKAGE_SUMMIT_ADAPTIVE_WW_INTF_NONE),y)
AWM_PARAMS += -F NONE
endif

ifneq ($(call qstrip,$(BR2_PACKAGE_SUMMIT_ADAPTIVE_WW_CFG_FILE)),)
AWM_PARAMS += -C $(BR2_PACKAGE_SUMMIT_ADAPTIVE_WW_CFG_FILE)
endif

ifeq ($(BR2_PACKAGE_ADAPTIVE_WW_CFG_WW),y)
define SUMMIT_ADAPTIVE_WW_CFG_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 -t $(TARGET_DIR)/usr/bin $(@D)/usr/bin/cww
endef
endif

define SUMMIT_ADAPTIVE_WW_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 -t $(TARGET_DIR)/usr/bin $(@D)/usr/bin/adaptive_ww

	$(INSTALL) -d "$(TARGET_DIR)/etc/default"
	echo "AWM_ARGS=$(AWM_PARAMS)" > $(TARGET_DIR)/etc/default/adaptive_ww

	$(SUMMIT_ADAPTIVE_WW_CFG_INSTALL_TARGET_CMDS)
endef

define SUMMIT_ADAPTIVE_WW_INSTALL_INIT_SYSTEMD
	$(INSTALL) -m 0644 -D $(@D)/usr/lib/systemd/system/adaptive_ww.service \
		$(TARGET_DIR)/usr/lib/systemd/system/adaptive_ww.service
endef

define SUMMIT_ADAPTIVE_WW_INSTALL_INIT_SYSV
	$(INSTALL) -m 0755 -D $(@D)/etc/init.d/adaptive_ww $(TARGET_DIR)/etc/init.d/S30adaptive_ww
endef

endif

$(eval $(generic-package))
